// Presentation and proof rules only. No model updates, network access, or persistence.
const SOURCE = 'https://data.cityofnewyork.us/d/erm2-nwe9';
const DAY = 86400000;
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const count = value => Math.max(0, Number(value) || 0).toLocaleString('en-US');
const placeName = value => String(value || 'this NYC block').toLowerCase().replace(/\b[a-z]/g, letter => letter.toUpperCase());
const recordPath = feature => `/f?id=${encodeURIComponent(feature.id)}`;
function buildRecordIndex(retained, active) {
  const index = new Map();
  for (const [features, archived] of [[retained, true], [active, false]]) {
    for (const original of features) {
      const feature = { ...original, record_archived: archived };
      index.set(feature.id, feature);
      for (const alias of feature.id_aliases || []) index.set(alias, feature);
    }
  }
  // A saved alias can lead through several successive canonical envelopes after refreshes.
  for (const [id, original] of index) {
    let feature = original;
    const seen = new Set();
    while (index.get(feature.id) && index.get(feature.id) !== feature && !seen.has(feature.id)) {
      seen.add(feature.id); feature = index.get(feature.id);
    }
    index.set(id, feature);
  }
  return index;
}
function eligibleRecord(feature) {
  return feature?.subject_type === 'encampment' && Boolean(String(feature.address || '').trim())
    && Number(feature.distinct_report_days) >= 5
    && Date.parse(feature.last_seen) - Date.parse(feature.first_seen) >= 30 * DAY
    && feature.source_url === SOURCE;
}
function outcomeProof({ claimAt, observations, quietDays, requiredDays, contradicted }) {
  const claim = Date.parse(claimAt);
  const priorPresence = Number.isFinite(claim) && observations.some(row => row.state === 'present' && Date.parse(row.observed_at) < claim);
  const later = observations.filter(row => Date.parse(row.observed_at) > claim);
  const absenceDays = new Set(later.filter(row => row.state === 'absent').map(row => row.observation_day)).size;
  const endpointAbsence = later.some(row => row.state === 'absent' && Date.parse(row.observed_at) >= claim + requiredDays * DAY);
  const recurrence = later.some(row => row.state === 'present');
  return { priorPresence, endpointAbsence, absenceDays, recurrence,
    held: Boolean(Number.isFinite(claim) && !contradicted && !recurrence && priorPresence && absenceDays >= 2 && endpointAbsence && quietDays != null && quietDays >= requiredDays) };
}
function date(value) {
  if (!value || !Number.isFinite(Date.parse(value))) return 'Not available';
  // Source report timestamps can be NYC wall time. Show their published calendar date without inventing UTC precision.
  return String(value).slice(0, 10);
}
const CSS = `:root{color-scheme:dark;--bg:#142722;--panel:#1d352d;--line:#466050;--ink:#f6f3e9;--muted:#bbc9c0;--accent:#72e2bd}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 system-ui,sans-serif}main{max-width:780px;margin:auto;padding:24px 22px 70px}nav{display:flex;justify-content:space-between;gap:20px;border-bottom:1px solid var(--line);padding-bottom:20px}a{color:var(--accent);text-underline-offset:4px}nav a{font-size:14px}h1{font-size:clamp(30px,7vw,48px);line-height:1.1;letter-spacing:-.035em;margin:14px 0}h2{font-size:20px;line-height:1.3;margin:0 0 12px}h3{font-size:16px}p{margin:10px 0}.eyebrow{font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:var(--accent);margin-top:32px}.muted,small{color:var(--muted)}.panel{padding:22px;margin:22px 0;background:var(--panel);border:1px solid var(--line);border-radius:14px}.facts{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.facts b{display:block;font-size:25px}.facts span{font-size:13px;color:var(--muted)}.actions{display:flex;flex-wrap:wrap;gap:12px;align-items:center}button,.button{font:inherit;font-weight:650;padding:12px 18px;min-height:46px;border-radius:8px;border:1px solid var(--accent);background:var(--accent);color:var(--bg);cursor:pointer;text-decoration:none}.secondary{background:transparent;color:var(--accent)}button:disabled{opacity:.5;cursor:wait}a:focus-visible,button:focus-visible,summary:focus-visible{outline:3px solid #fff;outline-offset:4px}summary{cursor:pointer}#check-status,#copy-status{min-height:26px}.list{list-style:none;padding:0}.list li{padding:20px 0;border-bottom:1px solid var(--line)}.list a{font-size:21px;font-weight:650}.proof{padding-left:22px}footer{font-size:13px;color:var(--muted);border-top:1px solid var(--line);padding-top:18px}@media(max-width:450px){main{padding:18px 16px 48px}.panel{padding:18px}.facts{gap:10px}.facts b{font-size:22px}.actions>*{flex-grow:1;text-align:center}}`;
function shell({ title, description, path, origin, indexable, body, featureId }) {
  const url = origin + path;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Curbnote</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${indexable ? 'index,follow' : 'noindex,follow'}"><link rel="canonical" href="${esc(url)}"><meta property="og:type" content="article"><meta property="og:site_name" content="Curbnote"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(url)}"><meta property="og:image" content="${esc(origin)}/assets/brand/curbnote-share-record-v1.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Curbnote. Every block has a story. Read the evidence. Check what changed."><meta name="twitter:image" content="${esc(origin)}/assets/brand/curbnote-share-record-v1.png"><meta name="twitter:card" content="summary_large_image"><style>${CSS}</style></head><body><main${featureId ? ` data-record-id="${esc(featureId)}"` : ''}><nav aria-label="Main"><a class="curbnote-lockup" href="/records"><img src="/assets/brand/curbnote-mark-v1.svg" width="36" height="36" alt="">Curbnote / NYC records</a><a href="/map">Map &amp; walking</a><a href="/feedback">Feedback</a></nav>${body}<footer>Public evidence about conditions, never people. Locations are approximate. Seek humane services, pedestrian access, named agency ownership and a dated follow-up. Nothing here sends a message or files a 311 report on your behalf.</footer></main>${featureId ? '<script src="/record-client.js" defer></script>' : ''}</body></html>`;
}
function renderRecord({ feature, loop, meta, origin, indexable }) {
  const place = placeName(feature.address || feature.addr);
  const title = `Recurring condition near ${place}`;
  const description = `NYC 311 evidence near ${place}, what nearby checks have reviewed, and what still needs follow-up. A closed ticket is not proof of resolution.`;
  const checks = loop.checks, proof = loop.durable_resolution, legacy = loop.record;
  const asOf = feature.nowcast?.as_of || meta?.generated_at;
  const refreshed = feature.record_source_refreshed_at || meta?.layer_freshness?.homelessness?.refreshed_at || meta?.sources?.nyc311?.refreshed_at;
  const stale = feature.record_archived || !refreshed || Date.now() - Date.parse(refreshed) > 7 * DAY || !Number.isFinite(Date.parse(refreshed));
  const label = stale ? 'Current status needs a fresh check' : feature.nowcast?.label || feature.condition?.label || 'Current status uncertain';
  const radius = Math.max(35, Math.min(90, Number(feature.location_uncertainty_m) || 45));
  const next = checks.pending > 0 && !checks.reviewed ? 'A nearby check is awaiting review.'
    : proof.verified_held ? 'Check whether the outcome is still holding.'
    : proof.claimed_clear ? 'Check whether the reported improvement held.'
    : checks.reviewed_present > 0 && legacy ? 'Use the reviewed evidence to prepare a follow-up.' : 'A fresh nearby check is the next useful step.';
  const canAct = checks.reviewed_present > 0 && legacy && !proof.claimed_clear && !proof.verified_held;
  const sourceDays = feature.distinct_report_days;
  const body = `<header><p class="eyebrow">NYC · Public condition record</p><h1>Near ${esc(place)}</h1><p>Recurring encampment reports · approximate area within about ${count(radius)} m. Reports may refer to different parts of this area.</p><p><a class="button" ${canAct ? 'data-record-event="action_open"' : ''} href="${esc(canAct ? legacy.href : checks.pending > 0 && !checks.reviewed ? '#reviewed' : '#nearby-check')}">${canAct ? 'Review history &amp; prepare an action' : checks.pending > 0 && !checks.reviewed ? 'See pending review' : 'Check this place'}</a></p></header>
<section class="panel" aria-labelledby="answer"><h2 id="answer">What is known here?</h2><p><strong>${esc(label)}.</strong></p><p class="muted">Last source report: ${esc(date(feature.last_seen))}. Model estimate dated ${esc(date(asOf))}. This is a heuristic reading of public evidence, not a measured probability or proof of current presence.${feature.record_archived ? ' This is retained history from an earlier data refresh. Leaving the current forecast map does not establish resolution.' : stale ? ' The source refresh is missing or more than seven days old; treat the estimate as stale.' : ''}</p><div class="facts"><div><b>${count(feature.count)}</b><span>source reports</span></div><div><b>${sourceDays == null ? '—' : count(sourceDays)}</b><span>distinct report days</span></div><div><b>${count(checks.reviewed)}</b><span>reviewed nearby checks · last 30 days</span></div></div><p><strong>City closure ≠ durable resolution.</strong> The reporting history establishes recurrence; it cannot tell us that a condition was continuously present.</p><details><summary>Source dates and how this record is grouped</summary><p>Source reports: ${esc(date(feature.first_seen))} to ${esc(date(feature.last_seen))}. Source refreshed: ${esc(date(refreshed))}.</p><p>${count(feature.location_identity?.reported_coordinate_groups || 1)} reported-coordinate group(s) in this bounded envelope. Nearby legacy records can use a different grouping and time window; their totals are shown separately below.</p><p><a href="${SOURCE}" rel="noreferrer">NYC 311 source dataset</a> · <a href="/methodology">Method and limitations</a></p></details></section>
<section class="panel" aria-labelledby="next"><h2 id="next">${esc(next)}</h2>${canAct ? `<p><a class="button" data-record-event="action_open" href="${esc(legacy.href)}">Review history &amp; prepare an action</a></p><p class="muted">You review the draft and choose whether to send it. A prepared receipt is not a sent action.</p>` : ''}<p>Nearby now? Check the public-space condition from a safe public place. Do not approach, identify or photograph people. “Can’t tell” is useful.</p><details id="nearby-check"${canAct ? '' : ' open'}><summary>Check this place</summary><p class="muted">Choosing an observation requests your location once to check proximity. Coordinates go to this server; the observation stores a rounded distance and a deduplication hash, not your raw location or route. No account required. Submissions wait for review.</p><div class="actions"><button type="button" data-check-state="present">Present</button><button type="button" class="secondary" data-check-state="absent">Not observed</button><button type="button" class="secondary" data-check-state="uncertain">Can’t tell</button></div><p id="check-status" role="status" aria-live="polite"></p></details><noscript><p>The nearby check needs JavaScript and location permission. You can still read and share this record's URL.</p></noscript></section>
<section aria-labelledby="reviewed"><h2 id="reviewed">Checks and outcome</h2><p>Last 30 days: ${count(checks.reviewed_present)} reviewed present · ${count(checks.reviewed_absent)} reviewed not observed · ${count(checks.reviewed_uncertain)} reviewed uncertain · ${count(checks.pending)} pending. Pending submissions do not change the estimate or establish an outcome.</p><p class="muted">${proof.clear_claim_time_semantics === 'public_record_last_seen_proxy' ? 'The public record has gone quiet; this is a proxy for a clear claim, not an observed improvement.' : proof.clear_claim_at ? `Clear claim dated ${esc(date(proof.clear_claim_at))}; it still needs reviewed follow-up.` : 'No supported clear claim has completed the proof requirements.'}</p><p><strong>${proof.verified_held ? 'Reviewed evidence supports an outcome that held.' : proof.claimed_clear ? 'Clear is claimed; durable resolution is not yet established.' : 'Durable resolution has not been established.'}</strong></p><ul class="proof"><li>Reviewed presence before clear claim: ${proof.reviewed_prior_presence ? 'recorded' : 'not established'}.</li><li>Reviewed absence on ${count(proof.reviewed_absence_days)} distinct day(s) after the claim.</li><li>Required quiet window: ${count(proof.required_quiet_days)} days. An absence check at or beyond its endpoint: ${proof.reviewed_endpoint_absence ? 'recorded' : 'not established'}.</li></ul><p class="muted">A later presence check or reporting recurrence reopens the loop. Review is not proof of independent observers; the pilot coordinator verifies that separately.</p></section>
${legacy ? `<section class="panel" aria-labelledby="history"><h2 id="history">Related city response history</h2><p>This older approximate-block record is ${count(legacy.distance_m)} m from the source envelope's anchor. Its grouping differs; these totals must not be added to the source totals above.</p><p>${count(legacy.reports)} legacy reports · ${count(legacy.city_closures)} city closures · ${count(legacy.returns_after_closure)} closures followed by another report.</p><a data-record-event="history_open" href="${esc(legacy.href)}">Inspect response history and action options</a></section>` : '<p>No compatible legacy response record is linked. A nearby check is still useful; missing history is not proof of resolution.</p>'}
<section class="panel"><h2>Bring a neighbor into the follow-up</h2><p>Share this record with someone who knows the block. Ask what changed, including whether nothing was observed. Bookmark it and return after review or the next check.</p><div class="actions"><button id="copy-record" type="button" class="secondary">Copy record link</button><a href="/map?mode=forecast&amp;id=${encodeURIComponent(feature.id)}">Inspect on the map / walking</a></div><p id="copy-status" role="status" aria-live="polite"></p><p class="muted"><small>We count aggregate record views and useful steps without analytics location data or a server-side visitor ID. Optional browser storage remembers visits for up to 30 days. Counts are not verified people or outcomes.</small></p></section>`;
  return shell({ title, description, path: recordPath(feature), origin, indexable, body, featureId: feature.id });
}
function renderDirectory(features, origin, query = '', total = features.length) {
  return shell({ title: 'NYC block condition records', description: 'Look up recurring NYC block conditions, inspect the public evidence, and help verify what changed.', path: '/records', origin, indexable: !query,
    body: `<p class="eyebrow">NYC · Public condition records</p><h1>What changed on your block?</h1><p>See what public evidence supports, check what changed, and follow the response through to a reviewed outcome.</p><form action="/records" method="get" class="panel" role="search"><label for="record-search">Find a block by street or address</label><div class="actions" style="margin-top:10px"><input id="record-search" name="q" value="${esc(query)}" maxlength="100" placeholder="e.g. East 20 Street" style="min-width:0;flex:1;font:inherit;padding:12px;border-radius:8px;border:1px solid var(--line);background:var(--bg);color:var(--ink)"><button type="submit">Search</button></div><p class="muted">Searches the NYC encampment records currently available here. Coverage is incomplete; results describe reports, not neighborhood safety.</p></form><h2>${query ? `Matching records (${count(total)})` : 'Start with a block you know'}</h2><p class="muted">${query ? 'Showing up to 30 matches. Refine the address to narrow the results.' : 'These three example records show how reporting history, nearby checks and follow-up fit together.'}</p><ul class="list">${features.map(f => `<li><a href="${esc(recordPath(f))}">Near ${esc(placeName(f.address || f.addr))}</a><p>Recurring encampment reports · last source report ${esc(date(f.last_seen))}${f.record_archived ? ' · retained history, current status unknown' : ''}</p></li>`).join('') || '<li>No matching records are available. Missing data does not mean a condition is resolved. Try a street name or the map search.</li>'}</ul><section class="panel"><h2>Explore the map or plan a walk</h2><p>Missing data does not mean a condition is resolved.</p><p>Use the map to inspect public evidence and plan around selected conditions. A nearby check along a regular walk helps establish what changed.</p><a class="button" href="/map">Open map &amp; walking</a></section><p>City closures are claims, not proof of durable resolution. Useful checks include present, not observed and uncertain. Reviewed follow-up is how we find out what changed.</p>` });
}
module.exports = { eligibleRecord, recordPath, renderRecord, renderDirectory, outcomeProof, buildRecordIndex };
